### ISSUE TITLE
Solved: USER Error running data generation script

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/tax-microdata-benchmarking#93] opened 2024-05-28 12:00 UTC
@nikhilwoodruff, after properly updating [tax-microdata-benchmarking](https://github.com/PSLmodels/tax-microdata-benchmarking), I believe:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/e0b9c0df-72f3-4388-b598-dccc7f0c5436)

and running make data, the main datasets appear to be created properly:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/7be37467-5256-4104-80fe-8fadd790e5a2)

and we pass all tests until we come to test_create_taxcalc_tmd_file:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/139464da-c79d-4b41-b117-08b5dc3c5fed)

The error appears to be related to policyengine_us:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/79b58aa8-dabd-4908-a6ab-229ffd16e4ee)

It looks to me like some kind of yaml error, perhaps related to TANF benefits in California counties, but I don't really know:

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/333342c4-c140-4a95-9fb9-c51363ebcf54)
...
![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/0bc4c765-50bc-4156-98b7-701aba34e92d)

Is it possible that I need to update policyengine_us? I had assumed install part of make would handle that.

If that's not it, and if it's an error in policyengine_us code seemingly unrelated to what we need (that is, we haven't had any discussions about TANF in California as being needed in our tax analysis), then this heightens the issue we discussed in our last call - the challenge of relying on frequently updated code that is extensive and includes much information not central to our task. In that case, we should make sure we put dealing with this high on our agenda.

I had hoped to help @martinholmer explore the Social Security questions in #83 but need the tmd files for that. Would be great if you can look into this, @nikhilwoodruff, or let me know what I am doing wrong.

**Comment by donboyd5** [comment] 2024-06-18 11:50
@nikhilwoodruff cc: @martinholmer 

After fetching upstream and checkout benchmarking branch, we still fail latest test, "test_flat_file.py::test_create_taxcalc_tmd_file", apparently based on something in policyengine_us:


![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/c7dc1575-aa4c-4fe4-b8cb-3cc453c390c5)

**Comment by nikhilwoodruff** [comment] 2024-06-19 08:14
OK- still can't reproduce sorry! (And the GitHub action successfully runs the script). Though I've merged #90 and that might have changed some things- could you try again?

**Comment by donboyd5** [comment] 2024-06-19 13:09
@nikhilwoodruff , I'm sorry to say something's still not working. I was still getting errors so I decided to start completely from scratch. Perhaps I'm doing something wrong. Here's what I did:

- Opened terminal in WSL ubuntu
- Deleted my tax-microdata-benchmarking folder so that I can get a clean start
- Created a new clean environment, tmd, that only has python 3.10
- conda activate tmd
- git clone https://github.com/PSLmodels/tax-microdata-benchmarking.git
- cd to tax-microdata-benchmarking, then just to be 100% sure:
- git remote add upstream https://github.com/PSLmodels/tax-microdata-benchmarking.git
- git remote -v # verify
- git fetch upstream
- git checkout master
- git merge upstream/master
- git diff master upstream/master # verify my code is the same as upstream
- export the two access tokens
- make data
- everything is fine up through imputing pension contributions, then it errors on "Constructing hierarchical PUF" -- see screenshot below

Any idea what might be wrong? Thanks.

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/3b36374e-6d61-4946-b1f3-4f2836ad2493)

**Comment by donboyd5** [comment] 2024-06-19 15:58
@nikhilwoodruff @martinholmer @jdebacker 

Upgrading policyengine_us got me much closer to success but it was unable to run tests - see below. If I understand correctly, it is not recognizing tax_microdata_benchmarking as a module. Any idea what I might be doing wrong?

![image](https://github.com/PSLmodels/tax-microdata-benchmarking/assets/6538392/7717b88b-6201-476c-99f6-8a244e41d7c3)

**Comment by donboyd5** [comment] 2024-06-24 14:56
@nikhilwoodruff @martinholmer 

I have determined that the error was on my end. I had python 3.10 in the active environment, but I had installed policyengine_us in a python 3.11 environment. Upgrading my active environment to python 3.11 enabled tax-microdata-benchmarking to find policyengine_us, solving the problem.

**Comment by martinholmer** [comment] 2024-06-24 15:40
@donboyd5 said in issue #93:
> Upgrading my active environment to python 3.11 enabled `tax-microdata-benchmarking` to find `policyengine_us`, solving the problem.

Good!   Glad things are working OK on your computer now.

I'm closing #93 now, but if you have other problems raise a new issue.

**Closed by martinholmer** 2024-06-24 15:40 UTC
Labels: bug
